var tableConf = [
  {
    title: "单号",
    field: "FBillNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目",
    field: "FProjectName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "编码",
    field: "FInvCode",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 80,
    headerSort: false,
  },
  {
    title: "名称",
    field: "FInvName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "项目经理",
    field: "FManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "客户项目经理",
    field: "FCustManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "项目类型",
    field: "FProjectType",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "单价",
    field: "FPrice",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 100,
    headerSort: false,
  },
  {
    title: "含税单价",
    field: "FTaxPrice",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 100,
    headerSort: false,
  },
  {
    title: "数量",
    field: "FQty",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 60,
    headerSort: false,
  },
  {
    title: "单位",
    field: "FUnitName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 60,
    headerSort: false,
  },
  {
    title: "金额",
    field: "FSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 100,
    headerSort: false,
  },
  {
    title: "含税金额",
    field: "FTaxSum",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
  {
    title: "税额",
    field: "FTax",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 100,
    headerSort: false,
  },
  {
    title: "税率",
    field: "FTaxRate",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 100,
    headerSort: false,
  },
  {
    title: "备注",
    field: "FMemo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 220,
    headerSort: false,
  },
  {
    title: "明细备注",
    field: "FEntryMemo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 220,
    headerSort: false,
  },
];
