var tableConf = [
  {
    title: "单号",
    field: "FBillNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目名称",
    field: "FProjectName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目编码",
    field: "FProjectCode",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "金额",
    field: "FTaxSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 100,
    headerSort: false,
  },
  {
    title: "销售订单号",
    field: "FSOBillNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 200,
    headerSort: false,
  }
];
