var tableConf = [
  {
    formatter: "rownum",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 30,
    download: false,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FCreateDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "利润年度",
    field: "FYear",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 80,
    headerSort: false,
  },
  {
    title: "项目",
    field: "FProjectName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目类型",
    field: "FProjectType",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "合同号",
    field: "FContractNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  // {
  //   title: "主合同净收入",
  //   field: "FSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  // {
  //   title: "增补合同金额",
  //   field: "FAddSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  {
    title: "预算金额",
    field: "FTotalSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "项目经理",
    field: "FManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户项目经理",
    field: "FCustManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "制单人",
    field: "FBillerName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
];
