var tableConf = [
  {
    formatter: "rownum",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 30,
    download: false,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FCreateDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目",
    field: "FProjectName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  // {
  //   title: "利润年度",
  //   field: "FYear",
  //   headerHozAlign: "center",
  //   hozAlign: "center",
  //   width: 80,
  //   headerSort: false,
  // },
  {
    title: "合同号",
    field: "FContractNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "项目类型",
    field: "FProjectType",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
  {
    title: "竣工时间",
    field: "FEndDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 120,
    headerSort: false,
  },
  {
    title: "预算金额",
    field: "FBudgetSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  // {
  //   title: "预算增补合同金额",
  //   field: "FBudgetAddSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  // {
  //   title: "预算总金额",
  //   field: "FBudgetTotalSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  // {
  //   title: "合同净收入",
  //   field: "FCostSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  // {
  //   title: "成本增补合同金额",
  //   field: "FCostAddSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  {
    title: "净成本",
    field: "FCostSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "预算与实际成本差额",
    field: "FDiffSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  // {
  //   title: "差异增补合同金额",
  //   field: "FDiffAddSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 120,
  //   headerSort: false,
  // },
  // {
  //   title: "预算与实际成本差额",
  //   field: "FSum",
  //   headerHozAlign: "center",
  //   hozAlign: "right",
  //   width: 160,
  //   headerSort: false,
  // },
  {
    title: "项目经理",
    field: "FManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户项目经理",
    field: "FCustManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "制单人",
    field: "FBillerName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
  },
];
