var tableConf = [
  {
    formatter: "rownum",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 30,
    download: false,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FCreateDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目",
    field: "FProjectName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "合同号",
    field: "FContractNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "预算合同金额",
    field: "FSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "预算增补合同金额",
    field: "FAddSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "预算总金额",
    field: "FTotalSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "成本合同金额",
    field: "FCostSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "成本增补合同金额",
    field: "FCostAddSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "成本总金额",
    field: "FCostTotalSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "差异合同金额",
    field: "FDiffSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "差异增补合同金额",
    field: "FDiffAddSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "差异成本总金额",
    field: "FDiffTotalSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "项目经理",
    field: "FManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户项目经理",
    field: "FCustManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "制单人",
    field: "FBillerName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
];
