var tableConf = [
  {
    formatter: "rownum",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 30,
    download: false,
    headerSort: false,
  },
  {
    title: "单号",
    field: "FBillNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目编码",
    field: "FProjectCode",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "销货金额",
    field: "FSourceSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false, formatter: "money",
    formatterParams: {
      decimal: ",",
      thousand: ".",
      precision: 2,
    },
  },
  {
    title: "结算金额",
    field: "FAccountSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false, formatter: "money",
    formatterParams: {
      decimal: ",",
      thousand: ".",
      precision: 2,
    },
  },
  {
    title: "制单人",
    field: "FBillerName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "单据状态",
    field: "FStatus",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 100,
    headerSort: false,
    formatter: function (cell, formatterParams, onRendered) {
      var val = cell.getValue();
      return "<div>" + (val ? "已审批" : "未审批") + "</div>";
    },
  },
  {
    title: "审核人",
    field: "FVeriferName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "审核日期",
    field: "FVerifyDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "备注",
    field: "FMemo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 250,
    headerSort: false,
  },
];
