var tableConf = [
  {
    formatter: "rownum",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 30,
    download: false,
    headerSort: false,
  },
  {
    title: "日期",
    field: "FCreateDate",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户",
    field: "FCustName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "项目",
    field: "FProjectName",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 180,
    headerSort: false,
  },
  {
    title: "合同号",
    field: "FContractNo",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "合同金额",
    field: "FSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "增补合同金额",
    field: "FAddSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "总金额",
    field: "FTotalSum",
    headerHozAlign: "center",
    hozAlign: "right",
    width: 120,
    headerSort: false,
  },
  {
    title: "项目经理",
    field: "FManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
  {
    title: "客户项目经理",
    field: "FCustManager",
    headerHozAlign: "center",
    hozAlign: "center",
    width: 150,
    headerSort: false,
  },
];
